docker:
    path: .
id: 29fb9b6a-21b2-451b-9963-ad7441a271d9
ide:
    filename: ide.yaml
name: capstone-fa-llm
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags/conveyor
    version: "2"
